### ISSUE TITLE
Package names retrieved from "winget list" are truncated

### ISSUE THREAD

**Issue by Programie** [VoSs2o0o/WinGetPgk#1]
I'm trying to use this Puppet module to remove some of the default apps installed in Windows 11.

As this module only knows packages installable with winget (i.e. those not having an empty source in `winget list`), I've patched it to also return those packages (by removing the check whether the source is empty).

But, due to the nature of winget truncating the columns in the output, the package names are also truncated. For example, instead of `Microsoft.WindowsSoundRecorder_8wekyb3d8bbwe` wingetpkg only reports `Microsoft.WindowsSoundRecorder_8wekyb3`.

Using the following in my Puppet code won't work as the resource does not exist:
```puppet
wingetpkg { "Microsoft.WindowsSoundRecorder_8wekyb3d8bbwe":
  ensure => absent
}
```

Specifying the truncated package name also does not work as winget can't find the package by that name.

I've already searched for a solution to prevent winget from truncating the output. The only way which might could fix that issue would be to use the PowerShell cmdlet `Get-WinGetPackage` which is currently in "preview" state in the latest winget release and also requires PowerShell 7.x (which is not installed by default).

**Comment by VoSs2o0o** [comment]
So far I know, you cannot uninstall software, on which Winget have no information about. The uninstall infos are part of the winget package manifest. To uninstall known software (not in the winget database) you can use the "exec" ressource.

**Comment by Programie** [comment]
It works using `winget uninstall <package>`. For example, I can uninstall the Sound Recorder from my example above using `winget uninstall Microsoft.WindowsSoundRecorder_8wekyb3d8bbwe`. And the example above would also work if winget wouldn't truncate the output (if my patch for returning packages without a source is applied to the Puppet module).

Therefore my question: Are you aware of any other way to make this module more resistant against issues like truncated package names? As mentioned before, the only way I could imagine right now is by using the PowerShell cmdlets.

**Comment by VoSs2o0o** [comment]
OK, the "new" universal apps have a standard command for install/uninstall. 

For the Winget ressource, I see no easy way to implement this feature, because the winget-cmd has no feature for it. Also I cannot easily use the WinGet-Powershell Api in ruby. I don't want to rewrite the entire project.

Maybe the Puppet Powershell module can resolve your problem via 
"Remove-AppxProvisionedPackage" or with a Powershellscript, that uses the winget-api commands.

**Comment by Programie** [comment]
OK, I will give the Powershell module a try. Thanks!
